### ISSUE TITLE
Add paper_trail gem compatibility

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo-diff_field#1]
This has been extracted from our friends from Greenhats and they use `audited`.
It would be nice to add `paper_trail` compatibility.
If that's too difficult, let's created another one for that.

**Comment by Paul-Bob** [comment]
Just noticed this issue, `paper_trail` compatibility was introduced here:

- https://github.com/avo-hq/avo-diff_field/commit/8fb59fc20db3a441a8e6089af89237afb86f00af
- https://github.com/avo-hq/avo-diff_field/commit/8049d49baac117a73aaf2074ca5c717089c070e7
